title: "Daniel Bzura"
description: "Security Engineer | CTO | Community Builder"
theme: minima

# Navigation links
nav:
  - name: "About"
    link: /about
  - name: "Projects"
    link: /projects
  - name: "Volunteering"
    link: /volunteering
  - name: "Orly FC"
    link: /orlyfc
